services:
  redisdb:
    image: redis:latest
    command: redis-server --appendonly yes --maxmemory 16gb --maxmemory-policy allkeys-lru --maxclients 1048576
    container_name: requestrepo_redisdb
    restart: unless-stopped
    volumes:
      - requestrepo-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
  backend:
    image: adrgs/requestrepo-backend:latest
    container_name: requestrepo_backend
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - JWT_SECRET=changethis
      - DOMAIN=localhost
      - SERVER_IP=130.61.138.67
      - TXT=Hello!
      - INCLUDE_SERVER_DOMAIN=true
      - SUBDOMAIN_ALPHABET=abcdefghijklmnopqrstuvwxyz0123456789
      - SUBDOMAIN_LENGTH=8
      - REDIS_HOST=requestrepo_redisdb
      - REDIS_TTL_DAYS=7
    depends_on:
      - redisdb
    volumes:
      - ./config/vendor:/app/ip2country/vendor/
      - ./config/cert:/app/cert
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
  dns:
    image: adgrs:requestrepo-dns:latest
    container_name: requestrepo_dns
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - JWT_SECRET=changethis
      - DOMAIN=localhost
      - SERVER_IP=ip-adress
      - TXT=Hello!
      - INCLUDE_SERVER_DOMAIN=true
      - SUBDOMAIN_ALPHABET=abcdefghijklmnopqrstuvwxyz0123456789
      - SUBDOMAIN_LENGTH=8
      - REDIS_HOST=requestrepo_redisdb
      - REDIS_TTL_DAYS=7
    environment:
      - REDIS_HOST=requestrepo_redisdb
    depends_on:
      - redisdb
    healthcheck:
      test: ["CMD", "pgrep", "python3"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
volumes:
  requestrepo-data:
  requestrepo-redis:
